image:
  file: .gitpod.Dockerfile
tasks:
  - before: sudo mount -t tmpfs shm -osize=4096m /dev/shm
  - init: |
      flutter channel stable
      flutter upgrade
      yes | flutter doctor --android-licenses
      flutter doctor
      flutter pub get
      flutter build -v web
      
  - command: |
      flutter devices
      flutter run --web-port 8080 --web-renderer canvaskit
ports:
  - port: 5900
    onOpen: ignore
    # vnc
  - port: 6080
    onOpen: open-preview
    # flutter
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - dart-code.flutter