image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      flutter doctor
      flutter pub get
  - command: |
      flutter devices
      flutter run --web-port 8080

ports:
  - port: 5900
    onOpen: ignore
    # vnc
  - port: 6080
    onOpen: open-preview
    # flutter
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - dart-code.flutter