tasks:
  - name: Install Flutter
    before: sudo mount -t tmpfs shm -osize=4096m /dev/shm
    init: |
      git clone https://github.com/flutter/flutter.git --depth 1 -b stable "/home/gitpod/flutter"
      echo 'export PATH="$PATH:/home/gitpod/flutter/bin:/home/gitpod/.pub-cache/bin"' >> /home/gitpod/.bashrc
      source /home/gitpod/.bashrc
      flutter precache
      flutter pub get
    command: |
      flutter run --web-port 5000 --web-renderer canvaskit
ports:
    # flutter
  - port: 5000
    onOpen: open-browser

vscode:
  extensions:
    - dart-code.flutter