// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'QUl6YVN5Q3Fhb05XWjc5VHhkSmloazJCU09TcUd5RDA3RHIwME5j',
    appId: 'MTo3ODQwNTMzNjc4NzI6d2ViOmZkMGU2ODg0N2ViMTMxNzdmYWRiYTU=',
    messagingSenderId: 'Nzg0MDUzMzY3ODcy',
    projectId: 'bWVtZWFtcHRvbg==',
    authDomain: 'bWVtZWFtcHRvbi5maXJlYmFzZWFwcC5jb20=',
    storageBucket: 'bWVtZWFtcHRvbi5hcHBzcG90LmNvbQ==',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'QUl6YVN5QmpTYWRSYzJQQndWR3ltLXh4WGZZOGM2cW1YUG5PdTlJ',
    appId: 'MTo3ODQwNTMzNjc4NzI6YW5kcm9pZDozZWIwYTMwMDI4NTNiMmEyZmFkYmE1',
    messagingSenderId: 'Nzg0MDUzMzY3ODcy',
    projectId: 'bWVtZWFtcHRvbg==',
    storageBucket: 'bWVtZWFtcHRvbi5hcHBzcG90LmNvbQ==',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'QUl6YVN5Q2hicWJqLUV0WUZ1Q0d3bnVZLTBZWE43S2piT2wyT3Nv',
    appId: 'MTo3ODQwNTMzNjc4NzI6aW9zOjc4YTg2YTM4ZTY2YmVjMzFmYWRiYTU=',
    messagingSenderId: 'Nzg0MDUzMzY3ODcy',
    projectId: 'bWVtZWFtcHRvbg==',
    storageBucket: 'bWVtZWFtcHRvbi5hcHBzcG90LmNvbQ==',
    iosClientId:
        'Nzg0MDUzMzY3ODcyLWxmdXY5bnZhN2FlcDRsNXBzNWg0bTNyNjc4aHQxZXZqLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t',
    iosBundleId: 'Y2x1Yi5zb3Rvbi5tZW1lYW1wdG9u',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'QUl6YVN5Q2hicWJqLUV0WUZ1Q0d3bnVZLTBZWE43S2piT2wyT3Nv',
    appId: 'MTo3ODQwNTMzNjc4NzI6aW9zOjc4YTg2YTM4ZTY2YmVjMzFmYWRiYTU=',
    messagingSenderId: 'Nzg0MDUzMzY3ODcy',
    projectId: 'bWVtZWFtcHRvbg==',
    storageBucket: 'bWVtZWFtcHRvbi5hcHBzcG90LmNvbQ==',
    iosClientId:
        'Nzg0MDUzMzY3ODcyLWxmdXY5bnZhN2FlcDRsNXBzNWg0bTNyNjc4aHQxZXZqLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t',
    iosBundleId: 'Y2x1Yi5zb3Rvbi5tZW1lYW1wdG9u',
  );
}
